version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crud_tareas
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mariadb
    networks:
      - laravel-net

  mariadb:
    image: mariadb:11
    container_name: mariadb_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud_tareas
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel-net

volumes:
  dbdata:

networks:
  laravel-net:
